### ISSUE TITLE
Lack of support for python 3.11

### ISSUE THREAD

**Issue by PiotrMorawiec-TomTom** [tomtom-international/keepachangelog-manager#31]

**Comment by PiotrMorawiec-TomTom** [comment]
Checked on Python 3.11.1:
```
changelogmanager add                                                                                                                              ✔  10024  08:47:42
Traceback (most recent call last):
  File "/Users/morawiec/.pyenv/versions/bdt3111/bin/changelogmanager", line 5, in <module>
    from changelogmanager.__main__ import main
  File "/Users/morawiec/.pyenv/versions/3.11.1/envs/bdt3111/lib/python3.11/site-packages/changelogmanager/__main__.py", line 19, in <module>
    import llvm_diagnostics as logging
  File "/Users/morawiec/.pyenv/versions/3.11.1/envs/bdt3111/lib/python3.11/site-packages/llvm_diagnostics/__init__.py", line 22, in <module>
    from llvm_diagnostics.messages import (
  File "/Users/morawiec/.pyenv/versions/3.11.1/envs/bdt3111/lib/python3.11/site-packages/llvm_diagnostics/messages.py", line 37, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Users/morawiec/.pyenv/versions/3.11.1/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Users/morawiec/.pyenv/versions/3.11.1/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/morawiec/.pyenv/versions/3.11.1/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/morawiec/.pyenv/versions/3.11.1/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'llvm_diagnostics.messages.Range'> for field column_number is not allowed: use default_factory
```
